Repository basedosdados/queries-basedosdados, pull requests merged in 2023-06, with the labels that each got.

#30 [dbt] br_cvm_fi
  .gitignore
  dbt_project.yml
  models/br_cvm_fi/documentos_balancete.sql
  models/br_cvm_fi/documentos_carteiras_fundos_investimento.sql
  models/br_cvm_fi/documentos_extratos_informacoes.sql
  models/br_cvm_fi/documentos_informacao_cadastral.sql
  models/br_cvm_fi/documentos_informe_diario.sql
  models/br_cvm_fi/documentos_perfil_mensal.sql
  models/br_cvm_fi/schema.yml
Labels: table-approve

#35 [dbt] br_cvm_fi
  models/br_cvm_fi/documentos_balancete.sql
  models/br_cvm_fi/documentos_carteiras_fundos_investimento.sql
  models/br_cvm_fi/documentos_extratos_informacoes.sql
  models/br_cvm_fi/documentos_informacao_cadastral.sql
  models/br_cvm_fi/documentos_informe_diario.sql
  models/br_cvm_fi/documentos_perfil_mensal.sql
  models/br_cvm_fi/schema.yml
Labels: table-approve, sync-dbt-schema

#34 [dbt] br_me_comex_stat
  models/br_me_comex_stat/dicionario.sql
  models/br_me_comex_stat/ncm_importacao.sql
  models/br_me_comex_stat/schema.yml
Labels: table-approve

#31 [dados] br_me_caged
  dbt_project.yml
  models/br_me_caged/microdados_movimentacao.sql
  models/br_me_caged/microdados_movimentacao_excluida.sql
  models/br_me_caged/microdados_movimentacao_fora_prazo.sql
  models/br_me_caged/schema.yml
Labels: table-approve

#38 [dbt] br_bd_diretorios_brasil.empresa
  dbt_project.yml
  models/br_bd_diretorios_brasil/br_bd_diretorios_brasil__empresa.sql
  models/br_bd_diretorios_brasil/schema.yml
Labels: table-approve, sync-dbt-schema

#36 br_b3_cotacoes.dicionario
  models/br_b3_cotacoes/br_b3_cotacoes__dicionario.sql
  models/br_b3_cotacoes/schemas.yml
Labels: sync-dbt-schema

#43 test tbl approve
  models/br_me_caged/microdados_movimentacao.sql
  models/br_me_caged/microdados_movimentacao_excluida.sql
  models/br_me_caged/microdados_movimentacao_fora_prazo.sql
  models/br_me_caged/schema.yml
Labels: table-approve

#47 [dbt] Staging/test laura student
  models/test_dataset/schema.yaml
  models/test_dataset/test_table_laura.sql
Labels: table-approve

#48 [dbt] br_b3_cotacoes.dicionario
  models/br_b3_cotacoes/br_b3_cotacoes__dicionario.sql
  models/br_b3_cotacoes/schemas.yml
Labels: table-approve, sync-dbt-schema

#49 fix: testing tbl approve
  models/br_cvm_fi/documentos_balancete.sql
  models/br_cvm_fi/documentos_carteiras_fundos_investimento.sql
  models/br_cvm_fi/documentos_extratos_informacoes.sql
  models/br_cvm_fi/documentos_informacao_cadastral.sql
  models/br_cvm_fi/documentos_informe_diario.sql
  models/br_cvm_fi/documentos_perfil_mensal.sql
  models/br_cvm_fi/schema.yml
Labels: table-approve

#52 [fix] table-approve
  .github/workflows/scripts/sync_dbt_schema.py
  .github/workflows/scripts/table_approve.py
  .github/workflows/scripts/utils.py
  metadata.json
  models/br_cvm_fi/documentos_carteiras_fundos_investimento.sql
  models/br_cvm_fi/documentos_extratos_informacoes.sql
  models/br_cvm_fi/documentos_informacao_cadastral.sql
  models/fi/schema.yaml
  models/test_dataset/schema.yaml
Labels: table-approve, sync-dbt-schema

#53 chore: tb-approve for br_cvm_fi
  models/br_cvm_fi/documentos_carteiras_fundos_investimento.sql
  models/br_cvm_fi/documentos_extratos_informacoes.sql
  models/br_cvm_fi/documentos_informacao_cadastral.sql
  models/br_cvm_fi/documentos_informe_diario.sql
  models/br_cvm_fi/documentos_perfil_mensal.sql
Labels: table-approve

#54 chore: tb-approve for br_cvm_fi
  .github/workflows/scripts/backend.py
  .github/workflows/scripts/sync_dbt_schema.py
  metadata.json
  models/br_cvm_fi/documentos_carteiras_fundos_investimento.sql
  models/br_cvm_fi/documentos_extratos_informacoes.sql
  models/br_cvm_fi/documentos_informacao_cadastral.sql
  models/br_cvm_fi/documentos_informe_diario.sql
  models/br_cvm_fi/documentos_perfil_mensal.sql
  models/br_cvm_fi/schema.yml
  models/br_rj_isp_estatisticas_seguranca/schema.yml
  models/br_rj_isp_estatisticas_seguranca/schemas.yml
  models/fi/schema.yaml
  models/test_dataset/schema.yml
Labels: table-approve, sync-dbt-schema

#55 chore: trigger tb-approve for br_cvm_fi
  models/br_cvm_fi/documentos_carteiras_fundos_investimento.sql
  models/br_cvm_fi/documentos_extratos_informacoes.sql
  models/br_cvm_fi/documentos_informacao_cadastral.sql
  models/br_cvm_fi/documentos_informe_diario.sql
  models/br_cvm_fi/documentos_perfil_mensal.sql
Labels: table-approve

#56 chore: trigger dbt deploy
  models/br_cvm_fi/documentos_carteiras_fundos_investimento.sql
  models/br_cvm_fi/documentos_extratos_informacoes.sql
  models/br_cvm_fi/documentos_informacao_cadastral.sql
  models/br_cvm_fi/documentos_informe_diario.sql
  models/br_cvm_fi/documentos_perfil_mensal.sql
Labels: table-approve, sync-dbt-schema

#58 [test] testing tbl approve
  metadata.json
  models/br_me_caged/microdados_movimentacao.sql
  models/br_me_caged/microdados_movimentacao_excluida.sql
  models/br_me_caged/microdados_movimentacao_fora_prazo.sql
  models/br_me_caged/schema.yml
Labels: table-approve, sync-dbt-schema

#60 [dbt] br_me_comex_stat
  models/br_me_comex_stat/schema.yml
Labels: table-approve

#50 [dbt] br_b3_cotacoes
  metadata.json
  models/br_b3_cotacoes/br_b3_cotacoes__cotacoes.sql
  models/br_b3_cotacoes/br_b3_cotacoes__dicionario.sql
  models/br_b3_cotacoes/schema.yml
Labels: table-approve, sync-dbt-schema

#66 [dbt] br_me_comex_stat
  models/br_me_comex_stat/schema.yml
Labels: table-approve

#81 [dbt] br_anatel_banda_larga_fixa
  metadata.json
  models/br_anatel_banda_larga_fixa/br_anatel_banda_larga_fixa__densidade_brasil.sql
  models/br_anatel_banda_larga_fixa/br_anatel_banda_larga_fixa__densidade_municipio.sql
  models/br_anatel_banda_larga_fixa/br_anatel_banda_larga_fixa__densidade_uf.sql
  models/br_anatel_banda_larga_fixa/schema.yml
  models/br_anatel_banda_larga_fixa/schemas.yml
  models/br_b3_cotacoes/schema.yml
  models/br_me_caged/schema.yml
Labels: table-approve, sync-dbt-schema

#83 [dbt] br_banda_larga_fixa
  models/br_anatel_banda_larga_fixa/br_anatel_banda_larga_fixa__densidade_uf.sql
  models/br_anatel_banda_larga_fixa/schema.yml
Labels: table-approve

#84 [dbt] mundo_transfermarkt_competicoes
  dbt_project.yml
  models/mundo_transfermarkt_competicoes/brasileirao_serie_a.sql
  models/mundo_transfermarkt_competicoes/schema.yml
Labels: table-approve

#85 [dbt] mundo_transfermarkt_competicoes
  models/mundo_transfermarkt_competicoes/brasileirao_serie_a.sql
Labels: table-approve

#77 [dbt] br_rj_isp_estatisticas_seguranca
  models/br_rj_isp_estatisticas_seguranca/relacao_cisp_aisp_risp.sql
  models/br_rj_isp_estatisticas_seguranca/schema.yml
  models/br_rj_isp_estatisticas_seguranca/schemas.yml
Labels: table-approve, sync-dbt-schema
