Repository basedosdados/queries-basedosdados, pull requests merged in 2024-10, with the labels that each got.

#787 br_sfb_sicar
  dbt_project.yml
  models/br_sfb_sicar/br_sfb_sicar__area_imovel.sql
  models/br_sfb_sicar/br_sfb_sicar__dicionario.sql
  models/br_sfb_sicar/schema.yml
Labels: table-approve, hacktoberfest-accepted

#788 [dbt] br_inep_censo_educacao_superior
  models/br_inep_censo_educacao_superior/br_inep_censo_educacao_superior__curso.sql
  models/br_inep_censo_educacao_superior/br_inep_censo_educacao_superior__ies.sql
  models/br_inep_censo_educacao_superior/schema.yml
Labels: table-approve

#791 [dbt]br_tse_filiacao_partidaria__microdados_antigos, novo custom_test e macro
  dbt_project.yml
  macros/validate_date_range.sql
  models/br_tse_filiacao_partidaria/br_tse_filiacao_partidaria__microdados_antigos.sql
  models/br_tse_filiacao_partidaria/schema.yml
  tests/generic/custom_null_proportion_multiple_columns.sql
Labels: table-approve, test-dev-model, hacktoberfest-accepted

#794 [dbt] br_inep_educacao_especial
  dbt_project.yml
  models/br_inep_educacao_especial/br_inep_educacao_especial__distorcao_idade_serie.sql
  models/br_inep_educacao_especial/br_inep_educacao_especial__docente_aee.sql
  models/br_inep_educacao_especial/br_inep_educacao_especial__docente_formacao.sql
  models/br_inep_educacao_especial/br_inep_educacao_especial__etapa_ensino.sql
  models/br_inep_educacao_especial/br_inep_educacao_especial__faixa_etaria.sql
  models/br_inep_educacao_especial/br_inep_educacao_especial__localizacao.sql
  models/br_inep_educacao_especial/br_inep_educacao_especial__matricula_aee.sql
  models/br_inep_educacao_especial/br_inep_educacao_especial__sexo_raca_cor.sql
  models/br_inep_educacao_especial/br_inep_educacao_especial__taxa_rendimento.sql
  models/br_inep_educacao_especial/br_inep_educacao_especial__tempo_ensino.sql
  models/br_inep_educacao_especial/br_inep_educacao_especial__tipo_deficiencia.sql
  models/br_inep_educacao_especial/code/educacao_especial_aee_docente.ipynb
  models/br_inep_educacao_especial/code/educacao_especial_aee_matricula.ipynb
  models/br_inep_educacao_especial/code/educacao_especial_distorcao_idade_serie.ipynb
  models/br_inep_educacao_especial/code/educacao_especial_formacao_docente.ipynb
  models/br_inep_educacao_especial/code/educacao_especial_taxa_rendimento.ipynb
  models/br_inep_educacao_especial/schema.yml
  models/br_inep_sinopse_estatistica_educacao_basica/schema.yml
Labels: table-approve

#795 [dbt] br_me_rais
  models/br_me_rais/br_me_rais__dicionario.sql
  models/br_me_rais/br_me_rais__microdados_estabelecimentos.sql
  models/br_me_rais/br_me_rais__microdados_vinculos.sql
  models/br_me_rais/code/rais_estabelecimento.ipynb
  models/br_me_rais/code/rais_vinculo.ipynb
  models/br_me_rais/schema.yml
Labels: hacktoberfest-accepted

#797 [dbt] br_me_rais
  models/br_me_rais/br_me_rais__dicionario.sql
  models/br_me_rais/br_me_rais__microdados_estabelecimentos.sql
  models/br_me_rais/br_me_rais__microdados_vinculos.sql
Labels: table-approve, hacktoberfest-accepted

#799 [fix] br_ms_cnes
  models/br_ms_cnes/br_ms_cnes__dicionario.sql
Labels: table-approve

#803 [fix] br_ms_sim.dicionario
  models/br_ms_sim/br_ms_sim__dicionario.sql
Labels: table-approve

#802 [dbt] br_inep_sinopse_estatistica_educacao_basica.docente
  models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_deficiencia.sql
  models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_escolaridade.sql
  models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_etapa_ensino.sql
  models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_faixa_etaria_sexo.sql
  models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_localizacao.sql
  models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__docente_regime_contrato.sql
  models/br_inep_sinopse_estatistica_educacao_basica/code_docente/docente_deficiencia.py
  models/br_inep_sinopse_estatistica_educacao_basica/code_docente/docente_escolaridade.py
  models/br_inep_sinopse_estatistica_educacao_basica/code_docente/docente_faixa_etaria_sexo.py
  models/br_inep_sinopse_estatistica_educacao_basica/code_docente/docente_localizacao.py
  models/br_inep_sinopse_estatistica_educacao_basica/code_docente/docente_regime_contratacao.py
  models/br_inep_sinopse_estatistica_educacao_basica/code_docente/docentes_etapa_ensino.py
  models/br_inep_sinopse_estatistica_educacao_basica/schema.yml
Labels: table-approve, test-dev-model
