Repository basedosdados/queries-basedosdados, pull requests merged in 2024-08, with the labels that each got.

#715 fix: despesas_funcao 3.01.122
  models/br_me_siconfi/br_me_siconfi__municipio_despesas_funcao.sql
  models/br_me_siconfi/code/compatibilizacao/despesas_funcao.xlsx
Labels: table-approve

#426 [dados] br_mec_sisu
  dbt_project.yml
  models/br_mec_sisu/br_mec_sisu__microdados.sql
  models/br_mec_sisu/schema.yml
Labels: table-approve, test-dev-model

#718 [Fix]br_mec_sisu
  models/br_mec_sisu/br_mec_sisu__microdados.sql
Labels: table-approve

#716 [dbt] br_rf_cno
  dbt_project.yml
  macros/custom_get_where_subquery.sql
  models/br_rf_cno/br_rf_cno__areas.sql
  models/br_rf_cno/br_rf_cno__cnaes.sql
  models/br_rf_cno/br_rf_cno__dicionario.sql
  models/br_rf_cno/br_rf_cno__microdados.sql
  models/br_rf_cno/br_rf_cno__vinculos.sql
  models/br_rf_cno/schema.yml
Labels: table-approve

#720 br_inep_ideb.brasil: fix col rede
  models/br_inep_ideb/br_inep_ideb__brasil.sql
  models/br_inep_ideb/schema.yml
Labels: table-approve, test-dev-model

#722 fix: cep and empresas directory
  models/br_bd_diretorios_brasil/br_bd_diretorios_brasil__cep.sql
  models/br_bd_diretorios_brasil/br_bd_diretorios_brasil__empresa.sql
Labels: table-approve

#727 [dbt] br_inep_sinopse_estatistica_educacao_basica__educacao_especial
  models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__educacao_especial_etapa_ensino.sql
  models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__educacao_especial_faixa_etaria.sql
  models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__educacao_especial_localizacao.sql
  models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__educacao_especial_sexo_raca_cor.sql
  models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__educacao_especial_tempo_ensino.sql
  models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__educacao_especial_tipo_deficiencia.sql
  models/br_inep_sinopse_estatistica_educacao_basica/schema.yml
Labels: table-approve, test-dev-model

#707 [dados] br_rf_arrecadacao
  dbt_project.yml
  models/br_rf_arrecadacao/br_rf_arrecadacao__uf.sql
  models/br_rf_arrecadacao/code/clean_data.py
  models/br_rf_arrecadacao/code/download_data.py
  models/br_rf_arrecadacao/schema.yml
Labels: table-approve, test-dev-model

#697 dbt: add world_oecd_pisa.student
  models/world_oecd_pisa/schema.yml
  models/world_oecd_pisa/world_oecd_pisa__student.sql
Labels: table-approve

#731 fix: measurement unit to x1000
  models/br_ibge_pib/br_ibge_pib__municipio.sql
Labels: table-approve

#730 Correção de `br_inep_ideb.uf` para 2021
  models/br_inep_ideb/br_inep_ideb__uf.sql
  models/br_inep_ideb/code/fix_ideb_uf_2021.py
  models/br_inep_ideb/schema.yml
Labels: table-approve, test-dev-model

#734 [dbt]: add `br_inep_ideb.regiao`
  models/br_inep_ideb/br_inep_ideb__regiao.sql
  models/br_inep_ideb/schema.yml
Labels: table-approve, test-dev-model

#735 [dbt]: `br_inep_ideb.{uf,brasil}`
  models/br_inep_ideb/br_inep_ideb__brasil.sql
  models/br_inep_ideb/br_inep_ideb__uf.sql
  models/br_inep_ideb/code/ideb_2023.py
Labels: table-approve

#736 Ideb 2023: atualizar tabela `municipio` e `escola`
  models/br_inep_ideb/br_inep_ideb__escola.sql
  models/br_inep_ideb/br_inep_ideb__municipio.sql
  models/br_inep_ideb/code/ideb_2023.py
  models/br_inep_ideb/schema.yml
Labels: table-approve, test-dev-model

#744 [fix] br_me_caged
  models/br_me_caged/br_me_caged__dicionario.sql
Labels: test-dev-model

#746 [dados] br_cgu_beneficios_cidadao__auxilio_emergencial
  models/br_cgu_beneficios_cidadao/br_cgu_beneficios_cidadao__auxilio_emergencial.sql
Labels: table-approve

#742 [fix] br_bd_diretorios_mundo.nomenclatura_comum_mercosul
  models/br_bd_diretorios_mundo/br_bd_diretorios_mundo__nomenclatura_comum_mercosul.sql
Labels: table-approve

#749 [dados] br_tse_eleicoes: despesas_candidato|receitas_candidato
  models/br_tse_eleicoes/br_tse_eleicoes__despesas_candidato.sql
  models/br_tse_eleicoes/br_tse_eleicoes__receitas_candidato.sql
  models/br_tse_eleicoes/schema.yml
Labels: table-approve, test-dev-model

#747 [dados] br_cgu_emenda_parlamentar
  dbt_project.yml
  models/br_cgu_emenda_parlamentar/br_cgu_emenda_parlamentar__microdados.sql
  models/br_cgu_emenda_parlamentar/schema.yml
Labels: table-approve, test-dev-model

#752 [dados] br_cgu_emendas_parlamentes
  dbt_project.yml
  models/br_cgu_emendas_parlamentares/br_cgu_emendas_parlamentares__microdados.sql
  models/br_cgu_emendas_parlamentares/schema.yml
Labels: table-approve

#753 [fix] br_cgu_emendas_parlamentares
  models/br_cgu_emendas_parlamentares/br_cgu_emendas_parlamentares__microdados.sql
Labels: table-approve
