Repository basedosdados/queries-basedosdados, pull requests merged in 2024-03, with the labels that each got.

#467 [dbt]: update `br_ibge_censo_2022`
  .gitignore
  models/br_ibge_censo_2022/br_ibge_censo_2022__domicilio_canalizacao_abastecimento_agua_municipio.sql
  models/br_ibge_censo_2022/br_ibge_censo_2022__domicilio_destino_lixo_municipio.sql
  models/br_ibge_censo_2022/br_ibge_censo_2022__domicilio_esgotamento_sanitario_municipio.sql
  models/br_ibge_censo_2022/br_ibge_censo_2022__domicilio_ligacao_abastecimento_agua_municipio.sql
  models/br_ibge_censo_2022/br_ibge_censo_2022__domicilio_quantidade_esgotamento_sanitario_municipio.sql
  models/br_ibge_censo_2022/br_ibge_censo_2022__domicilio_tipo_municipio.sql
  models/br_ibge_censo_2022/br_ibge_censo_2022__morador_cor_raca_destino_lixo_municipio.sql
  models/br_ibge_censo_2022/br_ibge_censo_2022__morador_cor_raca_esgotamento_sanitario_municipio.sql
  models/br_ibge_censo_2022/br_ibge_censo_2022__morador_cor_raca_ligacao_abastecimento_agua_municipio.sql
  models/br_ibge_censo_2022/br_ibge_censo_2022__morador_cor_raca_tipo_domicilio_municipio.sql
  models/br_ibge_censo_2022/schema.yml
Labels: table-approve

#477 [dbt]: br_mp_pep_cargos_funcoes add dbt alias
  models/br_mp_pep/br_mp_pep__cargos_funcoes.sql
  models/br_mp_pep/schema.yml
Labels: table-approve

#482 [dados] world_ampas_oscar
  dbt_project.yml
  models/world_ampas_oscar/schema.yml
  models/world_ampas_oscar/world_ampas_oscar__winner_demographics.sql
Labels: table-approve

#486 br_cgu_dados_abertos
  models/br_cgu_dados_abertos/br_cgu_dados_abertos__conjunto.sql
  models/br_cgu_dados_abertos/br_cgu_dados_abertos__organizacao.sql
  models/br_cgu_dados_abertos/br_cgu_dados_abertos__recurso.sql
Labels: table-approve

#488 [fix] world_ampas_oscar
  models/world_ampas_oscar/schema.yml
  models/world_ampas_oscar/world_ampas_oscar__winner_demographics.sql
Labels: table-approve

#494 remove last file in storage
  models/br_camara_dados_abertos/br_camara_dados_abertos__deputado_ocupacao.sql
Labels: table-approve

#487 fix table-approve with parquet files
  .github/workflows/scripts/table_approve.py
  models/br_cgu_dados_abertos/br_cgu_dados_abertos__conjunto.sql
  models/br_cgu_dados_abertos/br_cgu_dados_abertos__organizacao.sql
  models/br_cgu_dados_abertos/br_cgu_dados_abertos__recurso.sql
Labels: table-approve

#496 [dbt] br_cgu_beneficios_cidadao
  models/br_cgu_beneficios_cidadao/br_cgu_beneficios_cidadao__auxilio_brasil.sql
  models/br_cgu_beneficios_cidadao/br_cgu_beneficios_cidadao__bolsa_familia_pagamento.sql
  models/br_cgu_beneficios_cidadao/schema.yml
Labels: table-approve

#503 [dados-atualizacao]: update caged 01-24
  models/br_me_caged/microdados_movimentacao.sql
  models/br_me_caged/microdados_movimentacao_excluida.sql
  models/br_me_caged/microdados_movimentacao_fora_prazo.sql
Labels: table-approve

#501 [dbt] Fix Geobr Municipio
  models/br_geobr_mapas/br_geobr_mapas__municipio.sql
  models/br_geobr_mapas/schema.yml
Labels: table-approve

#509 [update] update auxilio brasil date 2021/11 and 2021/12
  models/br_cgu_beneficios_cidadao/br_cgu_beneficios_cidadao__auxilio_brasil.sql
Labels: table-approve

#515 [update/fix] br_mme_consumo_energia_eletrica
  .user.yml
  dbt_project.yml
  models/br_mme_consumo_energia_eletrica/br_mme_consumo_energia_eletrica__uf.sql
  models/br_mme_consumo_energia_eletrica/code/energia_eletrica.ipynb
  models/br_mme_consumo_energia_eletrica/schema.yml
Labels: table-approve

#499 [dbt] br_ms_sia
  dbt_project.yml
  models/br_ms_sia/br_ms_sia__dicionario.sql
  models/br_ms_sia/br_ms_sia__producao_ambulatorial.sql
  models/br_ms_sia/schema.yml
Labels: table-approve

#518 [add] Action test dbt model
  .github/workflows/scripts/table_test.py
  .github/workflows/test_dbt_model.yaml
Labels: test-dev-model

#520 dbt: br_inep_censo_escolar.turma
  models/br_inep_censo_escolar/br_inep_censo_escolar__turma.sql
  models/br_inep_censo_escolar/code/main.py
  models/br_inep_censo_escolar/schema.yml
Labels: table-approve, test-dev-model
