Repository basedosdados/queries-basedosdados, pull requests merged in 2024-04, with the labels that each got.

#527 Remover 2023 da base `br_inep_censo_escolar.turma`
  models/br_inep_censo_escolar/br_inep_censo_escolar__turma.sql
Labels: table-approve

#525 [dbt] br_ms_sia
  models/br_ms_sia/br_ms_sia__producao_ambulatorial.sql
  models/br_ms_sia/br_ms_sia__psicossocial.sql
  models/br_ms_sia/schema.yml
Labels: table-approve

#539 add: br_ibge_pam models + code
  dbt_project.yml
  models/br_ibge_pam/br_ibge_pam__lavoura_permanente.sql
  models/br_ibge_pam/br_ibge_pam__lavoura_temporaria.sql
  models/br_ibge_pam/code/api_to_json.py
  models/br_ibge_pam/code/json_to_parquet.py
  models/br_ibge_pam/schema.yml
Labels: table-approve, test-dev-model

#543 add: br_ibge_pam all code files
  models/br_ibge_pam/br_ibge_pam__lavoura_permanente.sql
  models/br_ibge_pam/lavoura_permanente/code/api_to_json.py
  models/br_ibge_pam/lavoura_permanente/code/json_to_parquet.py
  models/br_ibge_pam/lavoura_temporaria/code/api_to_json.py
  models/br_ibge_pam/lavoura_temporaria/code/json_to_parquet.py
Labels: documentation

#554 [dbt] novos diretórios
  .github/workflows/check-bq-project-name.yml
  .github/workflows/scripts/check_sql_files.py
  models/br_bd_diretorios_mundo/br_bd_diretorios_mundo__nomenclatura_comum_mercosul.sql
  models/br_bd_diretorios_mundo/br_bd_diretorios_mundo__sistema_harmonizado.sql
  models/br_bd_diretorios_mundo/download_sh4_ncm.ipynb
  models/br_bd_diretorios_mundo/schema.yml
Labels: table-approve, test-dev-model

#552 [dbt]: add br_inep_ideb
  dbt_project.yml
  models/br_inep_ideb/br_inep_ideb__escola.sql
  models/br_inep_ideb/br_inep_ideb__municipio.sql
  models/br_inep_ideb/code/main.py
  models/br_inep_ideb/schema.yml
Labels: table-approve, test-dev-model

#560 [dbt]: fix `br_inep_sinopse_estatistica_educacao_basica.faixa_etaria`
  models/br_inep_sinopse_estatistica_educacao_basica/br_inep_sinopse_estatistica_educacao_basica__faixa_etaria.sql
  models/br_inep_sinopse_estatistica_educacao_basica/code/main.py
Labels: table-approve

#559 [dbt] br_me_comex_stat.dicionario
  models/br_me_comex_stat/br_me_comex_stat__dicionario.sql
  models/br_me_comex_stat/schema.yml
Labels: table-approve
